# Generated by Django 2.2 on 2019-05-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='emial',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='python36@aa.com', max_length=255),
        ),
    ]
